PREPROCESSOR_MACROS += STM32WLxx

CONFIG_CPU_CORTEX_M4 := y

DEVICE_HEADER := \"stm32wlxx.h\"

INCLUDE_DIRS += \
$(ST_HAL_DIR)/devices/STM32WL/Device/Include \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Inc \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Inc/Legacy

C_SRC += \
$(ST_HAL_DIR)/devices/STM32WL/Device/Source/Templates/system_stm32wlxx.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_adc_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_adc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_comp.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_cortex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_crc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_dac_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_dac.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_dma.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_exti.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_flash_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_flash.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_gpio.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_i2c.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_i2s.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_irda.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_iwdg.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_pwr.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_pwr_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_rcc_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_rcc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_rtc_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_rtc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_smartcard.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_spi.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_spi_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_tim_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_tim.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_uart.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_uart_ex.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_usart.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal_wwdg.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_hal.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_adc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_crc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_dac.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_dma.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_exti.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_gpio.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_i2c.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_pwr.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_rcc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_rtc.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_spi.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_lptim.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_tim.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_usart.c \
$(ST_HAL_DIR)/devices/STM32WL/HAL/Src/stm32wlxx_ll_utils.c
