INCLUDE_DIRS += \
framework/OS/Wrappers \
framework/OS/Wrappers/Messages \
framework/OS/Wrappers/Syscalls \
framework/OS/Wrappers/Thread

C_SRC += \
framework/OS/Wrappers/Messages/messages.c \
framework/OS/Wrappers/Syscalls/syscalls.c \
framework/OS/Wrappers/Thread/os_thread.c
