PREPROCESSOR_MACROS += STM32F411xE

CONFIG_CPU_CORTEX_M4 := y

DEVICE_HEADER := \"stm32f4xx.h\"

INCLUDE_DIRS += \
$(ST_HAL_DIR)/devices/STM32F4/Device/Include \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Inc \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Inc/Legacy

C_SRC += \
$(ST_HAL_DIR)/devices/STM32F4/Device/Source/Templates/system_stm32f4xx.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_adc_ex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_adc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_can.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_cec.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_cortex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_crc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_dac_ex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_dac.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_dma.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_eth.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_exti.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_flash_ex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_flash.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_gpio.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_hcd.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_i2c.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_i2s.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_irda.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_iwdg.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_mmc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_nand.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_nor.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_pccard.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_pcd_ex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_pcd.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_pwr.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_rcc_ex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_rcc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_rtc_ex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_rtc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_sd.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_smartcard.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_spi.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_sram.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_tim_ex.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_tim.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_uart.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_usart.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal_wwdg.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_hal.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_adc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_crc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_dac.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_dma.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_exti.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_fsmc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_gpio.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_i2c.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_pwr.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_rcc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_rtc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_sdmmc.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_spi.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_tim.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_usart.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_usb.c \
$(ST_HAL_DIR)/devices/STM32F4/HAL/Src/stm32f4xx_ll_utils.c
